### ISSUE TITLE
[0.7.4] Application crash when I click on "Original Page"

### ISSUE THREAD

**Issue by Rathorian** [Alkarex/EasyRSS#60]
Hello,

Since I updated EasyRSS to version 0.7.4 via F-Droid, when I click on "Original page" the application crashes and closes.

When I want to read with the "Version Mobilizer", it tells me that the content of the article could not be loaded.

My phone is a Xiaomi Redmi Note 8 Pro with Android 9

Here is a summary of the error I was able to recover:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setTextColor(int)' on a null object reference
	at org.freshrss.easyrss.VerticalSingleItemView$1.onTouch(VerticalSingleItemView.java:124)
	at android.view.View.dispatchTouchEvent(View.java:12550)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3079)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2727)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3085)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2684)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3085)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2684)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3085)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2684)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3085)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2684)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3085)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2684)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3085)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2684)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3085)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2684)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3085)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2684)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3085)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2684)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3085)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2684)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3085)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2684)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:445)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3465)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:403)
	at android.view.View.dispatchPointerEvent(View.java:12804)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5428)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5219)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4730)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4783)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4749)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4889)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4757)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4946)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4730)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4783)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4749)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4757)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4730)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7533)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7502)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7459)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7657)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:246)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6831)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:927)
```

thank you so much

**Comment by Alkarex** [comment]
Hello,
This is fixed by https://github.com/Alkarex/EasyRSS/issues/55#issuecomment-619387584
https://github.com/Alkarex/EasyRSS/issues/55#issuecomment-619387584

I will try to issue a new version in the coming days

**Comment by Alkarex** [comment]
https://github.com/Alkarex/EasyRSS/releases/tag/v0.7.6
